version: '3.7'
services:
  fast-api:
    container_name: fast-api
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - DB_URL=${DB_URL}
      - RABBIT_URL=${RABBIT_URL}
    ports:
      - "8000:80"
    volumes:
      - ./app/:/code/app
      - ./migrations/:/code/migrations/
    restart: on-failure
    networks:
      - rabbitmq_net

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=${ALGORITHM}
      - DB_URL=${DB_URL}
    volumes:
      - ./app/:/code/app
      - ./tests/:/code/tests

  postgresql3:
    image: postgres
    ports:
      - 5432:5432
    env_file:
      - ./.env
    volumes:
      - /var/cache/postgres_data3:/var/lib/postgresql3/data

  rabbitmq:
    image: "rabbitmq:3-management"
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_PASSWORD=&{RABBITMQ_DEFAULT_PASS}
    networks:
      - rabbitmq_net
networks:
  rabbitmq_net:
    driver: bridge