version: '3.7'
services:
  fast-api:
    container_name: fast-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    volumes:
      - ./app/:/code/app
    restart: on-failure


    